name: testing
token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6ImRlZXBha2tvbmtpbWFsbGEiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUiLCJleHAiOjQ4NDg3ODcxMjksImlhdCI6MTYwODc4NzEyOSwiaXNzIjoiREt1YmUifQ.OS01e9C00qKeVy9iPSESYCP11OSnCHjPmoAptSrwZUcWy0q_f-MDMaEI7T8qOiWlYNMhi1AmKGiOlP07rTxRgVpqY1pfegbOinCNOU--eX-5HUodq7Pl0SVtuyU3vQMw8nkBKzMhmAD0_IgBaDq7QfnJEJ-4rejPPfXWIsbE8uJFpKx6WHMu0SM-yMt9jmbm1mAC_OZZ6kTxexQjT9sDayJzdTRiZANpBenXY4mv_x5OnyjypX-xgtl5e-4Gw-48ssCeM6UHTX68bCeb-OWtTwyB8K2eROz8l9-imC2O80evNGYA3TRBPqi5N0gtfMNFW7ob3aAADOT2QDQ9STOqQg
parameters:
  class: training
  training:
    executor:
      choice: dkube
      dkube:
        framework:
          choice: tensorflow
          details:
            version: '2.0'
            image: ocdr/d3-datascience-tf-cpu:v2.0
    datums:
      workspace:
        data:
          name: oc:titanic3
          version: master
        script: python main.py
      models:
      - name: oc:mnist
        mountpath: "/opt/dkube/model/input"
      datasets:
      - name: oc:mnist
        mountpath: "/opt/dkube/input"
      outputs:
      - name: oc:mnist
        mountpath: "/opt/dkube/output"
    hyperparams:
      customkv: []
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    tags: []
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
