name: testing
token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6ImRlZXBha2tvbmtpbWFsbGEiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUiLCJkZXBsb3kiOmZhbHNlLCJleHAiOjQ4NjAzNzgwNzAsImlhdCI6MTYyMDM3ODA3MCwiaXNzIjoiRGt1YmUifQ.CfHm_t11GSxrPLHaWsQLPqBv2a-76n0nU_8SnsrVaMWRG4hfmJ-dv-3cQsDYWV-RGP-Cy5VSKcbmoq14d4CFkdPIqeVVhTYj-LERWnPNJ186ikrdye2v4sCAWz5j6TwQsuvFst_VsbeE6cgXjdNBFmPIuA1xnJ6zJlRRYw1J9qTImkjAyvCdkJzyPWDPHfqgNZVSo6mM_XClvLAWT8tYlqOH0vUPzBqSycy0vBkbfDHIaf-yLSjEGoy0CydndcsTiC1ob2dujyaLjuk_sxyUDfo37FNIo7sUuvUR3IpIYlnZDrThGYzq9BdJRD6GKTZQBhPkhMdM0s3rk52X8gw8oQ
parameters:
  class: training
  training:
    executor:
      choice: dkube
      dkube:
        framework:
          choice: tensorflow
          details:
            version: '1.14'
            image: ocdr/d3-datascience-tf-cpu:v1.14-5
    datums:
      workspace:
        data:
          name: deepakkonkimalla:mnist-tf14
          version: master
        script: python model.py
      datasets:
      - name: deepakkonkimalla:mnist-tf14
        mountpath: "/opt/dkube/input"
      outputs:
      - name: deepakkonkimalla:mnist-tf14
        mountpath: "/opt/dkube/output"
    hyperparams:
      customkv: []
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    tags: []
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
